platform :ios, '13.1'
# use_frameworks!

target 'iOS_Bootstrap_Example' do
  pod 'iOS_Bootstrap', :path => '../'
  pod 'RxCocoa', '~> 4.0'
  # pod 'RealmSwift'
  pod 'SVGKit'
  pod 'Resolver', '~> 1.1.1'

  target 'iOS_Bootstrap_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings.delete('CODE_SIGNING_ALLOWED')
            config.build_settings.delete('CODE_SIGNING_REQUIRED')
        end
    end
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end

